kernel/src/scheduler.rs

A bit of code cleanup, and tackling a few todos before kfs-5 milestone

Scheduler code cleanup

---

libuser/src/ipc/macros.rs
libuser/src/ipc/server.rs

Allows the functions of an Object to access an instance of its WaitableManager, for instance to add a new Session to wait on.

Allow Object functions to access WaitableManager

---

kernel/src/interrupts/syscalls.rs
kernel/src/paging/bookkeeping.rs
kernel/src/paging/mapping.rs
kernel/src/paging/mod.rs
libuser/src/lib.rs
libuser/src/syscalls.rs
libutils/src/lib.rs

First implementation of QueryMemory. It is lacking two things:
- PageInfo, which I need to RE from Horizon/NX
- The paging's MappingType needs to be enriched to properly map to MemoryType

Implement QueryMemory

---

kernel/src/interrupts/syscalls.rs
kernel/src/ipc/port.rs
kernel/src/ipc/session.rs
libuser/src/ipc/macros.rs
libuser/src/ipc/mod.rs
libuser/src/ipc/server.rs
libuser/src/sm.rs
libuser/src/syscalls.rs

Lots of small, incremental improvements.

Ipc improvements

---

kernel/src/i386/gdt.rs
kernel/src/i386/mod.rs
kernel/src/i386/process_switch.rs
kernel/src/i386/structures/idt.rs
kernel/src/interrupts/mod.rs
kernel/src/main.rs

Kernel - Moved gdt/mod.rs to i386/gdt.rs

---

kernel/src/frame_allocator/i386.rs

kernel - fix frame_allocator overflow

---

kernel/src/frame_allocator/i386.rs

fix frame_allocator for the billionth and a half time

---

README.md

It's amazing. Let's add a badge to our readme to show how much I love it.

A bit of dependabot promotion.

---

.github/mergeable.yml

Enforces our merge requirements.

Add mergeable config.

---

kernel/src/i386/stack.rs
kernel/src/interrupts/syscalls.rs
kernel/src/paging/process_memory.rs

kernel: query_memory never fails

---

kernel/src/elf_loader.rs
kernel/src/main.rs

kernel: map_grub_module -> Result

---

libuser/src/terminal.rs

Removing terminal font todos

---

kernel/src/devices/pic.rs
kernel/src/event.rs
kernel/src/interrupts/syscalls.rs

kernel: PIC - registering to an irq unmasks it

---

libuser/src/sm.rs

Closes #42
```
gg
=
G
```
3 months

fix sm.rs indentation

---

libuser/src/lib.rs

Apparently this works now. Closes #67

global_allocator_cfg_not_test

---

libuser/src/terminal.rs
libuser/src/vi.rs
libuser/src/window.rs
shell/src/main.rs
vi/src/main.rs

Say hello to KFS running in VirtualBox !

Terminal window size

---

kernel/src/mem.rs
kernel/src/paging/arch/i386/lands.rs
kernel/src/paging/arch/i386/mod.rs
kernel/src/paging/arch/i386/table.rs
kernel/src/paging/arch/mod.rs
kernel/src/paging/lands.rs

Moving land definitions to i386 module.

Paging lands arch specific

---

kernel/src/devices/rs232.rs
kernel/src/log_impl/filter/mod.rs

kernel: log_impl tests

---

vi/src/main.rs

vi: fix window cropping

---

libuser/src/lib.rs

Tests in modules were not running because of libuser

libuser: re-enable tests

---

bootstrap/src/bootstrap_stack.rs
kernel/src/i386/stack.rs
libutils/src/lib.rs

Auto-calculate STACK_ALIGNMENT so we don't have to (forget to) manually update it in the future.

Kernel: Up kernel_stack pages to 8

---

libuser/src/allocator.rs

This one was a really nasty bug.

Libuser: Fix bug in heap extension

---

kernel/src/paging/arch/i386/table.rs
kernel/src/paging/hierarchical_table.rs
kernel/src/paging/mod.rs
kernel/src/paging/process_memory.rs
kernel/src/process.rs

Fix paging leak

---

Cargo.lock
swipc-parser/Cargo.toml

Use upstream pest 2.1

---

.travis.yml
Cargo.lock
Makefile.toml
swipc-gen/Cargo.toml
swipc-gen/src/itemmod.rs
swipc-gen/src/lib.rs

Ensure we build properly on OSX and Windows

---

kernel/src/main.rs

Cite the holy gospel PoC||GTFO.

This is gospel

---

Makefile.toml
kernel/src/devices/hpet.rs
kernel/src/devices/ioapic.rs
kernel/src/event.rs
kernel/src/i386/interrupt.rs
kernel/src/interrupts/irq.rs
kernel/src/interrupts/syscalls.rs

Shrodinger fix

---

Makefile.toml

Fix create-disk-if-not-exist

---

.travis.yml

CI: Disable caches, they break builds.

---

swipc-gen/src/gen_rust_code.rs

Fix multiple codegen bug in trait generation

swipc-gen: Fix multiple codegen bug in trait generation

---

swipc-gen/src/gen_rust_code.rs
swipc-parser/src/grammar.pest
swipc-parser/src/lib.rs

Various small QOL improvements to SwIPC.

Swipc improvements

---

kernel/src/cpu_locals.rs
kernel/src/panic.rs

Kernel: Fix TLS doc meme links

---

Makefile.toml
libuser/src/caps.rs
libuser/src/error.rs
libuser/src/ipc/mod.rs
libuser/src/ipc/server.rs
libuser/src/mem.rs
libuser/src/syscalls.rs
libuser/src/thread_local_storage.rs
libutils/src/io/mmio.rs
libutils/src/lib.rs
swipc-gen/src/gen_rust_code.rs
swipc-parser/src/lib.rs

Make doctests work on libraries, fix docs

---

.github/mergeable.yml

Fixes some issues with old mergeable. Hopefully, we'll be able to use upstream mergeable soon.

Update to mergeable v2

---

kernel/src/event.rs
kernel/src/ipc/port.rs
kernel/src/ipc/session.rs

This reduce the spam of logs when using INFO log level.

Use debug! when appropriate

---

libuser/src/terminal.rs
libuser/src/window.rs
shell/src/main.rs

Implement ls

---

fs/src/interface/storage.rs

Fix read_from_temp_storage assert

---

Makefile.toml

Oops.That shouldn't have gone through review.

Make FS use the correst Makefile rules

---

kernel/src/i386/interrupt_service_routines.rs

Sometimes, when running userspace, GS would be 0, leading to instructions accessing gs:[0] to fail with a null deref. I'm... still not entirely sure why that happens. It appears that our ring detection in trap_gate_asm fails, leading to gs not being changed before returning to userspace. But what confuses me is that when this happens, gs should be set to the kernel TLS, and not 0.
Anyways, this is fixed by pushing GS on the UserSpaceHardwareContext and restoring it unconditionally before returning.
Fixes (but we don't know why) #473

Kernel: Fix random userspace gs = 0

---

Makefile.toml

Fix broken args to qemu

---

libkern/src/lib.rs
libuser/src/argv.rs
libutils/src/lib.rs
loader/src/main.rs

Fix arguments loading/parsing

---

docs/BUILDING.md

Build instruction should use release mode for qemu

---

Makefile.toml
fs/src/main.rs
kernel/src/i386/process_switch.rs
kernel/src/process.rs
libuser/src/threads.rs

Each commit fixes a separate potentially bad bug. It should be reviewed commit by commit.

Various fixes

---

ahci/src/hba.rs

AHCI: Fix reading more than 256 sectors

---

Cargo.lock
ahci/src/disk.rs
disk-initializer/Cargo.toml
disk-initializer/src/gpt.rs
disk-initializer/src/main.rs
fs/Cargo.toml
fs/src/detail/driver/fat/directory.rs
fs/src/detail/driver/fat/file.rs
fs/src/detail/driver/fat/filesystem.rs
fs/src/detail/driver/fat/mod.rs
fs/src/detail/driver/mod.rs
fs/src/detail/gpt/mod.rs
fs/src/detail/mod.rs
fs/src/interface/driver.rs
fs/src/interface/storage.rs
fs/src/ipc/mod.rs
kernel/src/panic.rs
libuser/src/error.rs
libuser/src/lib.rs

Finally, after fixing a dozen of bugs. we'll be able to use the new and shiny StorageDevice and libfat improvements. @Thog this PR will make your tests a lot more bearable :^).

Update storage device

---

libuser/Cargo.toml

Needed for future std integration

Update libuser Cargo.toml

---

.github/workflows/rust.yml

actions: Attempt to fix build issues on Ubuntu

---

coreutils/src/date/date.rs

This update the subtree of coreutils that have a fix for date

Fix date command in coreutils

---

ipcdefs/loader.id
kernel/src/i386/interrupt_service_routines.rs
kernel/src/process.rs
kernel/src/syscalls.rs
libuser/build.rs
libuser/src/syscalls.rs
loader/src/main.rs
shell/src/main.rs

To do this, I had to implement svcGetProcessList and svcTerminateProcess.

Add ps and kill shell commands

---

Cargo.lock
Cargo.toml
Makefile.toml
df/Cargo.toml
df/src/main.rs
fs/src/detail/driver/fat/filesystem.rs
fs/src/detail/driver/mod.rs
fs/src/detail/mod.rs
fs/src/ipc/mod.rs
ipcdefs/filesystem.id
libuser/src/argv.rs
libuser/src/threads.rs
std_hello_world/src/main.rs

Implement df

---

ipcdefs/loader.id
libuser/src/argv.rs
loader/src/main.rs
rust/src/libstd/path.rs
rust/src/libstd/sys/sunrise/os.rs
rust/src/libstd/sys/sunrise/process.rs
shell/src/main.rs
std_hello_world/src/main.rs

Implement environment variables

---

kernel/src/scheduler.rs

Yes, I'm making a PR to fix some docs after months of silence. Don't mind me :D.

Fix broken docs in schedule function.
