sunriseos/SunriseOS

kernel/src/sync.rs

SpinLockIRQ should *not* derive Debug automatically, as that leads it to lock the spinlock without blocking IRQs! Instead, it should reimplement the Debug logic, calling its own try_lock function.

Fix buggy Debug implementation in SpinLockIRQ

---

kernel/src/error.rs
kernel/src/interrupts/syscalls.rs
kernel/src/process.rs
libuser/src/syscalls.rs
libuser/src/types.rs

This PR depends on #28 . **DO NOT MERGE BEFORE MERGING #28**
- Implements Create/Map/Unmap shared memory syscalls in kernelspace
- Implements the equivalent syscall in userspace
- Add SharedMemory and MappedSharedMemory userspace types.
- MappedSharedMemory contains some unsafe functions that should probably not
be used...

Implement SharedMemory

---

Cargo.lock
clock/src/vbe.rs
kernel/src/error.rs
libkern/src/error.rs
libkern/src/lib.rs
libuser/Cargo.toml
libuser/src/error.rs
libuser/src/ipc/macros.rs
libuser/src/ipc/mod.rs
libuser/src/ipc/server.rs
libuser/src/lib.rs
libuser/src/sm.rs
libuser/src/syscalls.rs
libuser/src/types.rs
shell/src/vbe.rs
sm/src/main.rs
vi/src/main.rs

- Move kernel UserspaceError to libkern KernelError
- Create a libuser::error::Error type, strongly typing all the errors.
- Make all the libuser syscalls return a KernelError type
- Make all the wrapper return a fat Error type.

Better userspace error handling

---

kernel/src/paging/hierarchical_table.rs

When the hole we were considering was too small, we should
continue searching from the end of the considered hole,
not restart searching in the same hole.

Fix find_virtual_space_aligned

---

.gitignore
.travis.yml
Cargo.toml
Makefile.toml
bootstrap/src/frame_alloc.rs
bootstrap/src/gdt/i386.rs
bootstrap/src/gdt/mod.rs
bootstrap/src/main.rs
bootstrap/src/paging/mod.rs
kernel/src/devices/rs232.rs
kernel/src/frame_allocator/i386.rs
kernel/src/heap_allocator.rs
kernel/src/i386/mod.rs
kernel/src/i386/registers.rs
kernel/src/log_impl/filter/mod.rs
kernel/src/main.rs
kernel/src/paging/arch/i386/mod.rs
kernel/src/paging/lands.rs
kernel/src/paging/mapping.rs
libuser/src/ipc/macros.rs
libuser/src/lib.rs
libuser/src/syscalls.rs
libutils/src/lib.rs

Running `cargo test` works now.
To achieve this i needed all crates to compile for the host architecture (only compile, not run properly, for now).
At first I tried to write a mockup i386 module with dummy functions that could be called from the tests which would cause no side-effect, but it made me realize quite the hard way that our arch-independent code relies **way to much** on i386 internal structures and functions, and my mockup module was several hundred lines long, exposing a TSS and all things like that, without being anywhere close from compiling.
So decided to change my strategy, forgot the mockup, and went for writing a lot of `#[cfg(not(test)]` in the parts that couldn't be linked with the std, and it eventually compiled successfully. 
Unfortunately, because we have no mockup …

cargo test

---

kernel/src/paging/mapping.rs

Now splitting a Shared/SystemResrved mapping is an error even when it's a no-op.
Fixes #84.

kernel - split mapping tests

---

Cargo.lock
kernel/src/i386/process_switch.rs
kernel/src/interrupts/syscalls.rs
kernel/src/main.rs
kernel/src/process.rs
libuser/src/syscalls.rs
shell/Cargo.toml
shell/src/main.rs

Re-enable the test_threads command from shell.
Some shenanigans were used to make it all work. The terminal is
passed by value to the test_threads function, which wraps it in
an Arc<Mutex> in order to share it between the two threads. Those
threads will then repeatedly try to lock it, and yield if they fail.
Yielding is important, since we lack preemption.
The argument is passed via EAX. This sucks because the C ABI expects
it on the stack, so we have to make a wrapper naked function that
pushes it... Maybe it should be the job of the kernel? On the other
hand, we're going to want a wrapper around test creation anyways.

Add argument handling to start_thread syscall.

---

kernel/src/interrupts/mod.rs

Exception handlers used to unschedule with some Arc strong references still in scope,
which had the effect of leaking them, and thread/process structs were never dropped.
Now the Arcs are in their own scope, and dropped before the call to unschedule.
Fixes #153

kernel: exception drops thread struct #whoopsie

---

Makefile.toml

qemu's `-d int` was nice when we were trying to make interruption work,
but now it's become a real pain.

Makefile: stop flooding log on every interrupt

---

kernel/src/process.rs
kernel/src/sync.rs

See #190 
This is not the final solution. API is still unsound, but it at least works when the invariants are upheld...

Go back to backup/restore SpinLockIRQ system

---

libuser/src/zero_box.rs

Box that bzero and does not stack overflow.
This module would ideally be in libutils, to be available to the kernel too,
but I didn't want to make libutils depend on alloc.
I considered extending Box<T> when T implements our trait,
instead of exposing some cheap wrapper.
I don't know what would have been better.

libuser: ZeroBox

---

ahci/src/main.rs
kernel/src/frame_allocator/physical_mem_region.rs
kernel/src/interrupts/syscalls.rs
kernel/src/process.rs
kernel/src/process/capabilities.rs
libkern/src/lib.rs
libuser/src/lib.rs
libuser/src/mem.rs
libuser/src/syscalls.rs
libuser/src/window.rs
vi/src/main.rs

- syscall MapMmioRegion
- syscall QueryPhysicalAddress
- moving some memory related functions of libuser in their own `mem` module
- improving the syscalls macro
- fixing the capabilities macro

Syscalls physical memory

---

libuser/src/error.rs

The module is stored on bits 0:8, so the mask is 0x1FF

libuser: fix error bitshift

---

.gitignore
Cargo.lock
Makefile.toml
ahci/Cargo.toml
ahci/src/disk.rs
ahci/src/fis.rs
ahci/src/hba.rs
ahci/src/main.rs
ahci/src/pci.rs
libuser/src/ahci.rs
libuser/src/error.rs
libuser/src/lib.rs
libuser/src/zero_box.rs

Introducing the driver for AHCI disks, for ATA and SATA devices.
Provides IPC endpoints to read and write some sectors.
For now it is a very modest single-threaded driver,
blocking on every request until the previous one is completed,
but this is prone to change as AHCI supports up to 32 simultaneous
outstanding commands.
closes #173 
closes #165

AHCI driver

---

shell/src/main.rs

When displaying a GIF, create a window the size of the gif.
Fixes #217

shell: gif window size

---

ahci/Cargo.toml
ahci/src/hba.rs
ahci/src/main.rs
bootstrap/Cargo.toml
bootstrap/src/main.rs
bootstrap/src/paging/mod.rs
bootstrap/src/paging/table.rs
kernel/Cargo.toml
kernel/src/i386/mod.rs
kernel/src/i386/structures/idt.rs
kernel/src/main.rs
kernel/src/paging/lands.rs

static_assertions remove labels

---

shell/src/main.rs

Rewrote the test_page_fault function in asm, because rust
used to optimize it out since it is extremely UB.
Fixes #223
I went and checked in GDB, and @roblabla was right, the match branch
was never taken, but instead we ended up in weird places.
Now it seems to be working... well, crashing ... well, doing what we expect.

shell: test_page_fault asm

---

kernel/src/checks.rs
kernel/src/error.rs
kernel/src/interrupts/syscalls.rs
kernel/src/ipc/session.rs
kernel/src/paging/process_memory.rs
libuser/src/error.rs
libuser/src/ipc/buffer.rs
libuser/src/ipc/macros.rs
libuser/src/ipc/mod.rs
libuser/src/ipc/server.rs

X/C Buffers

---

Makefile.toml
i386-unknown-none-user.json
kernel/src/elf_loader.rs
libuser/src/crt0/mod.rs
libuser/src/crt0/relocation.rs
libuser/src/lib.rs
linker-scripts/userspace.ld
shell/src/main.rs

This makes every userland programs position-independent.
This PR also correctly separates every section in its appropriate segment.

Support dynamic relocation in libuser

---

Makefile.toml

Set a default rule to the makefile, so it runs qemu when building without arguments.

Makefile: Set a default rule

---

Cargo.lock
clock/Cargo.toml
clock/src/main.rs
kernel/src/interrupts/syscalls.rs
kernel/src/log_impl/mod.rs
kernel/src/main.rs
libuser/src/ipc/macros.rs
libuser/src/ipc/server.rs
libuser/src/lib.rs
libuser/src/log_impl.rs
libuser/src/syscalls.rs
sm/src/main.rs
vi/src/main.rs

Brings three improvements:
- Puts some color on the log level, which is neat
- Allows filtering of logs coming from userspace applications in grub. We can now do `sunrise_clock=debug,info` to get more debug information from sunrise_clock, for instance.
- Makes the outputDebugString aware of the log formatting, which results in logs that look like the following:
```
[INFO] - sunrise_clock - clock - 13:59:48 Thursday 23 May 19
```
instead of the old:
```
[INFO] - sunrise_kernel::interrupts::syscalls - clock - [INFO] - sunrise_clock - 13:59:48 Thursday 23 May 19
```

Better logging - more colors, less duplication

---

scripts/README.md
scripts/gdb/README.md
scripts/gdb/break_userspace.py
scripts/gdb/gdbinit

This folder should only contain tools and utilities not essential to the compilation of SunriseOS, but which can help its debugging and development.

Infra: creating the scripts folder

---

libuser/src/ipc/server.rs

SM takes zero-padded service name encoded as an u64 integer so 8 should be included in the assert check.

ipc/server.rs: Fix typo in encode_bytes

---

kernel/src/ipc/session.rs
kernel/src/paging/cross_process.rs
libuser/src/ipc/buffer.rs
libuser/src/ipc/macros.rs
libuser/src/ipc/mod.rs
libuser/src/types.rs
swipc-gen/src/gen_rust_code.rs

Properly implement A/B/W buffers in kernel and implement B buffers in libuser.
Also, fix handle<copy> in object! macro.
This is needed by the upcoming time service PR.

 Properly implement A/B/W buffers

---

swipc-gen/src/gen_rust_code.rs

This makes sure that enum are safe to be used with IPC.

swipc-gen: Use enum_with_val! for enum

---

kernel/src/process.rs
libuser/src/types.rs
swipc-gen/src/gen_rust_code.rs

0xFFFF8000 and 0xFFFF8001 now point to the current thread and current
process respectively. Those meta-handles are valid in almost all
contexts.

Add process handle, and thread/proc meta-handles.

---

swipc-gen/src/gen_rust_code.rs
swipc-gen/src/lib.rs
swipc-gen/src/main.rs

`cargo make swipc-gen sunrise_libuser::vi ipcdefs/vi.id` will now generate a file under sunrise_libuser/src/vi.rs containing the module. You can simply turn the module declaration in sunrise_libuser/src/lib.rs into `mod vi;` and get better compilation errors.

More useful swipc-gen Makefile.toml rule.

---

libutils/src/lib.rs

Make `print_hexdump` follow the `xxd` hexdump format, so we can easily diff hexdumps.

Libutils: Hexdump xxd output format

---

Cargo.lock
kernel/Cargo.toml
kernel/src/ipc/session.rs
kernel/src/process/capabilities.rs
libuser/src/ipc/mod.rs
shell/Cargo.toml
shell/src/main.rs

This remove dependency on byteorder in the kernel and shell.
Also reduce usage of byteorder in libuser
Related to #332

Clean up usage of byteorder

---

bootstrap/src/gdt/mod.rs
linker-scripts/bootstrap.ld
linker-scripts/kernel.ld

The linker scripts for kernel and bootstrap now put `.rodata` in its own segment, so it can be read-only.
Fixes #369

Linker: kernel and bootstrap .rodata RO

---

time/build-script/Cargo.toml

Removes a C dependency that fails to compile sometimes on windows.
See https://github.com/alexcrichton/flate2-rs/issues/27

Use rust backend for miniz

---

scripts/gdb/gdbinit
scripts/gdb/get_frame_sizes.py

```
(gdb) get-frame-sizes
sunrise_libuser::main: 0x118
None: 0x20
real_start: 0x1c
core::ops::function::FnOnce::call_once: 0x20
Total stack size: 0x174
```

Add get-frame-sizes command

---

kernel/src/ipc/session.rs

I swear I should get banned from programming anything remotely unsafe.

Kernel: Properly copy the last page in buf_unmap

---

kernel/src/i386/gdt.rs
kernel/src/paging/arch/mod.rs
kernel/src/panic.rs
libuser/src/threads.rs

Because the TLS PR is so big, todobot bailed on it.
Make a PR that only touches every `// todo:` we opened in #339, so todobot picks them again.

todo-bot: touch TLS todos

---

libuser/src/thread_local_storage.rs
linker-scripts/userspace.ld

The symbols should now be an exact guess of the TLS segment's VirtAddr, FileSize, MemSize, and Align.
We no longer force the alignment, and use `MAX(ALIGNOF(.tbss), ALIGNOF(.tdata))` as a guess for the resulting alignment.

Libuser: fix TLS linker symbols

---

libuser/src/types.rs
sm/src/main.rs
time/src/main.rs

We used to have a bit of a hard-to-debug hang in sm when multiple
futures wait on SERVICE_EVENT. Here's what would happen: Multiple
futures would call get_service on a service that does not exist yet, and
end up waiting on SERVICE_EVENT. Let's call those services "a" and "b".
Then, a service "a" and "b" would both get registered through register_event.
This would cause the event to get triggered, waking up the service waiting on
"a". The future would check if the handle is actually triggered (to
handle spurious wakeups) with a call to wait_synchronization, and then
clear the event and return the session.
Then "b" gets woken up and goes through the same process. Except the
event was cleared, so the call to wait_synchronization will return
false!
The mistake is that when the future wakeup, …

SM: Fix hang when multiple futures wait on EVENT

---

Cargo.lock
ahci/Cargo.toml
kernel/Cargo.toml

We don't need to use our own fork anymore as it has been upstream.
Also make sure that AHCI doesn't use a specific version number.

Switch to bitfield official releases

---

isofiles/boot/grub/grub.cfg

load_video isn't defined and this cause an error to show on grub

Remove load_video in grub.cfg

---

kernel/src/i386/interrupt_service_routines.rs

When entering the kernel (e.g. syscall), we need to switch `gs` from GdtIndex::UTlsElf to GdtIndex::KTls, so the kernel can access its cpu-locals.
When re-entering the kernel (e.g. interrupt while handling a syscall), it would seem we don't need to switch `gs` again, since the first entry should have already done it for us. This was the politic that we followed.
However it turns out that sometimes during a syscall the cpu re-interrupts us while we're still in the first interrupt handler, before we had time to set `gs`. The second interrupt handler assumes gs is already valid, and we end up in the kernel with `gs` pointing to GdtIndex::UTlsElf: that's a page fault waiting to happen.
Fix this by unconditionally set `gs` to GdtIndex::KTls in interrupt handlers.

Kernel: unconditionally switch gs entering kernel

---

Makefile.toml
Xargo.toml
bootstrap/Cargo.toml
docs/BUILDING.md
docs/UPDATE_RUST.md
i386-unknown-sunrise-user.json
kernel/Cargo.toml
libuser/src/crt0/mod.rs
libuser/src/crt0/relocation.rs
libuser/src/lib.rs
libuser/src/syscalls.rs

This is the preparing steps for starting our own libstd.

Ground work for libstd (reuse Xargo)

---

libuser/src/threads.rs
shell/src/main.rs

This makes the stack size used by a thread configurable at creation time. (This is needed for libstd)

Add stack_size as Thread::create argument

---

libuser/src/argv.rs
libuser/src/lib.rs
loader/src/main.rs
sm/src/main.rs

Loader is now able to send arguments to programs. The programs are responsible with parsing the cmdline (instead of shell doing it). This is obviously very different from what happens on a unix OS, but again, we're just following the Horizon Way.

Add argument handling to loader.

---

kernel/src/i386/interrupt_service_routines.rs
kernel/src/process.rs
kernel/src/scheduler.rs
kernel/src/syscalls.rs
libuser/src/threads.rs
shell/src/main.rs

This allows to wait for a thread to be in an exit state.
Also rearrange ThreadState to be closer to Horizon states.

Implement Thread::join

---

Cargo.lock
Makefile.toml
ipcdefs/loader.id
kernel/src/error.rs
kernel/src/event.rs
kernel/src/i386/interrupt_service_routines.rs
kernel/src/main.rs
kernel/src/process.rs
kernel/src/syscalls.rs
libkern/src/error.rs
libkern/src/lib.rs
libkern/src/process.rs
libuser/src/error.rs
libuser/src/lib.rs
libuser/src/syscalls.rs
libuser/src/types.rs
loader/Cargo.toml
loader/src/elf_loader.rs
loader/src/main.rs
shell/src/main.rs

- Loader now has an interface to spawn new processes at runtime.
- We can also add Loader to wait until a process is killed.

Implement loader interface and waiting on process

---

ahci/src/hba.rs
kernel/src/i386/interrupt_service_routines.rs
kernel/src/syscalls.rs
libuser/src/mem.rs
libuser/src/syscalls.rs

Closes #203 
Our previous query_physical_address was super broken. The phys_offset in particular could, in certain conditions, return some absolutely absurd values.
While investigating this bug, I took some time to figure out how the HOS kernel really implements it, and found out that the documentation on switchbrew was actually super wrong, or at least misleading. So I fixed the implementation to remove the sunriseos extension phys_offset. Instead, now it implements it just like Nintendo, which means it returns three values:
- Physical Address of the base of the mapping
- Virtual Address of the base of the mapping
- Size of the mapping.
Where the mapping is the closest contiguous range of physical address below the given address.

Kernel: Make query_physical_memory work like HOS

---

Cargo.lock
Cargo.toml
Makefile.toml
ipcdefs/loader.id
ipcdefs/twili.id
keyboard/src/ps2.rs
libuser/src/ps2.rs
libuser/src/syscalls.rs
libuser/src/terminal.rs
libuser/src/types.rs
loader/src/main.rs
rust/src/libstd/Cargo.toml
rust/src/libstd/sys/sunrise/mod.rs
rust/src/libstd/sys/sunrise/process.rs
rust/src/libstd/sys/sunrise/stdio.rs
shell/src/main.rs
swipc-gen/src/gen_rust_code.rs
twili/Cargo.toml
twili/src/main.rs
vi/Cargo.toml
vi/src/terminal.rs

We now implement a twili service that's responsible for giving a process its stdin/stdout/stderr. Stderr is ignored for now, as it's used for panics, and having panics go to svcOutputDebugString is too useful.

Libstd stdout goes to terminal

---

kernel/src/devices/rs232.rs
kernel/src/i386/interrupt_service_routines.rs
kernel/src/process.rs
kernel/src/sync/mod.rs
kernel/src/sync/spin_lock.rs
kernel/src/sync/spin_lock_irq.rs

Fixes #471.
This involves creating a newtype wrapper around spin::Mutex to check when locking if the number of interrupts being serviced is currently zero.

 Panic if SpinLock locked in interrupt context

---

.github/workflows/rust.yml
Makefile.toml
docs/BUILDING.md

Ensure we build xargo and cargo-make in a reproducible way to prevent bitrot. We now specify a version and ask for a locked build. My understanding is that --locked will use the lockfile packaged by the crate, see https://github.com/rust-lang/cargo/issues/5654.

CI: Bitrot protection for dep installs.

---

Cargo.lock
keyboard/Cargo.toml
keyboard/src/ps2.rs

My goal here was to try to read from the port in as few places as possible (as well as trying to handle weird edge cases) in preparation for sending commands / receiving responses. In the process, though, I may have made `KeyEvent::read_key_event` an even more messy function than before...

Keyboard refactor

---

.github/workflows/rust.yml
Makefile.toml

Looks like CI broke due to some issue in our ancient cargo's implementation of git fetching. It's possible to work around it by asking cargo to use the system git tool instead, which may be slower, but will at least work.

Try to fix CI by forcing cargo to fetch git repos via git cmd
